spring:
  datasource:
    url: jdbc:mysql://1.55.215.214:3969/tland092020?allowMultiQueries=true&useAffectedRows=true
    user: root
    password: infocity12

server:
  port: 9191

mybatis:
  config: classpath:mybatis-config.xml
  type-aliases-package: com.info.model
  mapper-locations: /mapper/*.xml